[advanced]
prop=kernel.alveo_hls4ml.kernel_flags=-std=c++11
#param=compiler.normalizeDefaultMemoryBanks=true

[hls]
pre_tcl=./config.tcl

[connectivity]
# nk=<kernel name>:<number>:<cu_name>.<cu_name>...
nk=alveo_hls4ml:3:alveo_hls4ml_0.alveo_hls4ml_1.alveo_hls4ml_2
# slr=<compute_unit_name>:<slr_ID>

# sp=<compute_unit_name>.<interface_name>:<bank name> 
sp=alveo_hls4ml_0.in:HBM[0:3]
sp=alveo_hls4ml_0.out:HBM[4:7]
sp=alveo_hls4ml_1.in:HBM[8:11]
sp=alveo_hls4ml_1.out:HBM[12:15]
sp=alveo_hls4ml_2.in:HBM[16:19]
sp=alveo_hls4ml_2.out:HBM[20:23]

[clock]
freqHz=30000000

[vivado]
prop=run.impl_1.STEPS.OPT_DESIGN.IS_ENABLED=true
prop=run.impl_1.STEPS.OPT_DESIGN.ARGS.DIRECTIVE=Explore

prop=run.impl_1.STEPS.PLACE_DESIGN.ARGS.DIRECTIVE=AltSpreadLogic_high

prop=run.impl_1.STEPS.PHYS_OPT_DESIGN.IS_ENABLED=true
prop=run.imp1_1.STEPS.PHYS_OPT_DESIGN.ARGS.DIRECTIVE=Explore

prop=run.impl_1.STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE=Explore

prop=run.impl_1.STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED=true
prop=run.impl_1.STEPS.POST_ROUTE_PHYS_OPT_DESIGN.ARGS.DIRECTIVE=AggressiveExplore
