-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity alveo_hls4ml_myproject is
port (
    in_buf_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    in_buf_ce0 : OUT STD_LOGIC;
    in_buf_d0 : OUT STD_LOGIC_VECTOR (767 downto 0);
    in_buf_q0 : IN STD_LOGIC_VECTOR (767 downto 0);
    in_buf_we0 : OUT STD_LOGIC;
    in_buf_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    in_buf_ce1 : OUT STD_LOGIC;
    in_buf_d1 : OUT STD_LOGIC_VECTOR (767 downto 0);
    in_buf_q1 : IN STD_LOGIC_VECTOR (767 downto 0);
    in_buf_we1 : OUT STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_ce0 : OUT STD_LOGIC;
    out_buf_0_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_we0 : OUT STD_LOGIC;
    out_buf_0_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_ce1 : OUT STD_LOGIC;
    out_buf_0_d1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_q1 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_0_we1 : OUT STD_LOGIC;
    out_buf_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_ce0 : OUT STD_LOGIC;
    out_buf_1_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_we0 : OUT STD_LOGIC;
    out_buf_1_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_ce1 : OUT STD_LOGIC;
    out_buf_1_d1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_q1 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_1_we1 : OUT STD_LOGIC;
    out_buf_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_ce0 : OUT STD_LOGIC;
    out_buf_2_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_we0 : OUT STD_LOGIC;
    out_buf_2_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_ce1 : OUT STD_LOGIC;
    out_buf_2_d1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_q1 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_2_we1 : OUT STD_LOGIC;
    out_buf_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_ce0 : OUT STD_LOGIC;
    out_buf_3_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_we0 : OUT STD_LOGIC;
    out_buf_3_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_ce1 : OUT STD_LOGIC;
    out_buf_3_d1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_q1 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_3_we1 : OUT STD_LOGIC;
    out_buf_4_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_ce0 : OUT STD_LOGIC;
    out_buf_4_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_q0 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_we0 : OUT STD_LOGIC;
    out_buf_4_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_ce1 : OUT STD_LOGIC;
    out_buf_4_d1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_q1 : IN STD_LOGIC_VECTOR (12 downto 0);
    out_buf_4_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_buf_empty_n : IN STD_LOGIC;
    in_buf_read : OUT STD_LOGIC;
    i_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    out_buf_0_full_n : IN STD_LOGIC;
    out_buf_0_write : OUT STD_LOGIC;
    out_buf_1_full_n : IN STD_LOGIC;
    out_buf_1_write : OUT STD_LOGIC;
    out_buf_2_full_n : IN STD_LOGIC;
    out_buf_2_write : OUT STD_LOGIC;
    out_buf_3_full_n : IN STD_LOGIC;
    out_buf_3_write : OUT STD_LOGIC;
    out_buf_4_full_n : IN STD_LOGIC;
    out_buf_4_write : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of alveo_hls4ml_myproject is 
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv768_lc_1 : STD_LOGIC_VECTOR (767 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_ce0 : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_din : STD_LOGIC_VECTOR (12 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_write : STD_LOGIC;
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_write : STD_LOGIC;
    signal ap_channel_done_layer2_out_V_3 : STD_LOGIC;
    signal layer2_out_V_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer2_out_V_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer2_out_V_3 : STD_LOGIC;
    signal ap_channel_done_layer2_out_V_2 : STD_LOGIC;
    signal layer2_out_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer2_out_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer2_out_V_2 : STD_LOGIC;
    signal ap_channel_done_layer2_out_V_1 : STD_LOGIC;
    signal layer2_out_V_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer2_out_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer2_out_V_1 : STD_LOGIC;
    signal ap_channel_done_layer2_out_V : STD_LOGIC;
    signal layer2_out_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer2_out_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer2_out_V : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_start : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_idle : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_0 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_channel_done_layer4_out_V_3 : STD_LOGIC;
    signal layer4_out_V_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer4_out_V_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer4_out_V_3 : STD_LOGIC;
    signal ap_channel_done_layer4_out_V_2 : STD_LOGIC;
    signal layer4_out_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer4_out_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer4_out_V_2 : STD_LOGIC;
    signal ap_channel_done_layer4_out_V_1 : STD_LOGIC;
    signal layer4_out_V_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer4_out_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer4_out_V_1 : STD_LOGIC;
    signal ap_channel_done_layer4_out_V : STD_LOGIC;
    signal layer4_out_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer4_out_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer4_out_V : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_start : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_done : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_continue : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_idle : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready : STD_LOGIC;
    signal pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_return : STD_LOGIC_VECTOR (9 downto 0);
    signal layer5_out_V_full_n : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_start : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_idle : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_ready : STD_LOGIC;
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_layer7_out_V_4 : STD_LOGIC;
    signal layer7_out_V_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer7_out_V_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer7_out_V_4 : STD_LOGIC;
    signal ap_channel_done_layer7_out_V_3 : STD_LOGIC;
    signal layer7_out_V_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer7_out_V_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer7_out_V_3 : STD_LOGIC;
    signal ap_channel_done_layer7_out_V_2 : STD_LOGIC;
    signal layer7_out_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer7_out_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer7_out_V_2 : STD_LOGIC;
    signal ap_channel_done_layer7_out_V_1 : STD_LOGIC;
    signal layer7_out_V_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer7_out_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer7_out_V_1 : STD_LOGIC;
    signal ap_channel_done_layer7_out_V : STD_LOGIC;
    signal layer7_out_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer7_out_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer7_out_V : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_start : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_idle : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready : STD_LOGIC;
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_layer9_out_V_4 : STD_LOGIC;
    signal layer9_out_V_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer9_out_V_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer9_out_V_4 : STD_LOGIC;
    signal ap_channel_done_layer9_out_V_3 : STD_LOGIC;
    signal layer9_out_V_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer9_out_V_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer9_out_V_3 : STD_LOGIC;
    signal ap_channel_done_layer9_out_V_2 : STD_LOGIC;
    signal layer9_out_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer9_out_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer9_out_V_2 : STD_LOGIC;
    signal ap_channel_done_layer9_out_V_1 : STD_LOGIC;
    signal layer9_out_V_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer9_out_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer9_out_V_1 : STD_LOGIC;
    signal ap_channel_done_layer9_out_V : STD_LOGIC;
    signal layer9_out_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer9_out_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer9_out_V : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_start : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_idle : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready : STD_LOGIC;
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_0 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_3 : STD_LOGIC_VECTOR (5 downto 0);
    signal relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_channel_done_layer10_out_V_4 : STD_LOGIC;
    signal layer10_out_V_4_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer10_out_V_4 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer10_out_V_4 : STD_LOGIC;
    signal ap_channel_done_layer10_out_V_3 : STD_LOGIC;
    signal layer10_out_V_3_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer10_out_V_3 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer10_out_V_3 : STD_LOGIC;
    signal ap_channel_done_layer10_out_V_2 : STD_LOGIC;
    signal layer10_out_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer10_out_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer10_out_V_2 : STD_LOGIC;
    signal ap_channel_done_layer10_out_V_1 : STD_LOGIC;
    signal layer10_out_V_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer10_out_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer10_out_V_1 : STD_LOGIC;
    signal ap_channel_done_layer10_out_V : STD_LOGIC;
    signal layer10_out_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_layer10_out_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_layer10_out_V : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_start : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_done : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_continue : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_idle : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_i_read : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_ce0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_we0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_ce0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_we0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_ce0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_we0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_ce0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_we0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_ce0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_we0 : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_write : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_write : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_write : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_write : STD_LOGIC;
    signal dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_write : STD_LOGIC;
    signal i_c_i_full_n : STD_LOGIC;
    signal i_c_i_dout : STD_LOGIC_VECTOR (12 downto 0);
    signal i_c_i_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal i_c_i_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal i_c_i_empty_n : STD_LOGIC;
    signal layer2_out_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer2_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_empty_n : STD_LOGIC;
    signal layer2_out_V_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer2_out_V_1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_1_empty_n : STD_LOGIC;
    signal layer2_out_V_2_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer2_out_V_2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_2_empty_n : STD_LOGIC;
    signal layer2_out_V_3_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer2_out_V_3_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_3_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer2_out_V_3_empty_n : STD_LOGIC;
    signal layer4_out_V_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer4_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_empty_n : STD_LOGIC;
    signal layer4_out_V_1_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer4_out_V_1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_1_empty_n : STD_LOGIC;
    signal layer4_out_V_2_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer4_out_V_2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_2_empty_n : STD_LOGIC;
    signal layer4_out_V_3_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer4_out_V_3_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_3_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer4_out_V_3_empty_n : STD_LOGIC;
    signal layer5_out_V_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal layer5_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer5_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer5_out_V_empty_n : STD_LOGIC;
    signal layer7_out_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer7_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_empty_n : STD_LOGIC;
    signal layer7_out_V_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer7_out_V_1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_1_empty_n : STD_LOGIC;
    signal layer7_out_V_2_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer7_out_V_2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_2_empty_n : STD_LOGIC;
    signal layer7_out_V_3_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal layer7_out_V_3_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_3_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_3_empty_n : STD_LOGIC;
    signal layer7_out_V_4_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer7_out_V_4_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_4_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer7_out_V_4_empty_n : STD_LOGIC;
    signal layer9_out_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer9_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_empty_n : STD_LOGIC;
    signal layer9_out_V_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer9_out_V_1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_1_empty_n : STD_LOGIC;
    signal layer9_out_V_2_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer9_out_V_2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_2_empty_n : STD_LOGIC;
    signal layer9_out_V_3_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer9_out_V_3_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_3_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_3_empty_n : STD_LOGIC;
    signal layer9_out_V_4_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer9_out_V_4_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_4_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer9_out_V_4_empty_n : STD_LOGIC;
    signal layer10_out_V_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_V_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_empty_n : STD_LOGIC;
    signal layer10_out_V_1_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_V_1_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_1_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_1_empty_n : STD_LOGIC;
    signal layer10_out_V_2_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_V_2_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_2_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_2_empty_n : STD_LOGIC;
    signal layer10_out_V_3_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_V_3_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_3_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_3_empty_n : STD_LOGIC;
    signal layer10_out_V_4_dout : STD_LOGIC_VECTOR (5 downto 0);
    signal layer10_out_V_4_num_data_valid : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_4_fifo_cap : STD_LOGIC_VECTOR (1 downto 0);
    signal layer10_out_V_4_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component alveo_hls4ml_conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_buf_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        in_buf_ce0 : OUT STD_LOGIC;
        in_buf_q0 : IN STD_LOGIC_VECTOR (767 downto 0);
        i : IN STD_LOGIC_VECTOR (12 downto 0);
        i_c_i_din : OUT STD_LOGIC_VECTOR (12 downto 0);
        i_c_i_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        i_c_i_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        i_c_i_full_n : IN STD_LOGIC;
        i_c_i_write : OUT STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component alveo_hls4ml_relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component alveo_hls4ml_pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component alveo_hls4ml_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component alveo_hls4ml_normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component alveo_hls4ml_relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component alveo_hls4ml_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        i_dout : IN STD_LOGIC_VECTOR (12 downto 0);
        i_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        i_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        i_empty_n : IN STD_LOGIC;
        i_read : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (5 downto 0);
        out_buf_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_0_ce0 : OUT STD_LOGIC;
        out_buf_0_we0 : OUT STD_LOGIC;
        out_buf_0_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_1_ce0 : OUT STD_LOGIC;
        out_buf_1_we0 : OUT STD_LOGIC;
        out_buf_1_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_2_ce0 : OUT STD_LOGIC;
        out_buf_2_we0 : OUT STD_LOGIC;
        out_buf_2_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_3_ce0 : OUT STD_LOGIC;
        out_buf_3_we0 : OUT STD_LOGIC;
        out_buf_3_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_4_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        out_buf_4_ce0 : OUT STD_LOGIC;
        out_buf_4_we0 : OUT STD_LOGIC;
        out_buf_4_d0 : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component alveo_hls4ml_fifo_w13_d8_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (12 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component alveo_hls4ml_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component alveo_hls4ml_fifo_w6_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (5 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component alveo_hls4ml_fifo_w10_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0 : component alveo_hls4ml_conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_start,
        ap_done => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done,
        ap_continue => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue,
        ap_idle => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_idle,
        ap_ready => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_ready,
        in_buf_address0 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_address0,
        in_buf_ce0 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_ce0,
        in_buf_q0 => in_buf_q0,
        i => i,
        i_c_i_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_din,
        i_c_i_num_data_valid => i_c_i_num_data_valid,
        i_c_i_fifo_cap => i_c_i_fifo_cap,
        i_c_i_full_n => i_c_i_full_n,
        i_c_i_write => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_write,
        ap_return_0 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_0,
        ap_return_1 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_1,
        ap_return_2 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_2,
        ap_return_3 => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_3);

    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0 : component alveo_hls4ml_relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_start,
        ap_done => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done,
        ap_continue => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue,
        ap_idle => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_idle,
        ap_ready => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready,
        ap_ce => ap_const_logic_1,
        p_read => layer2_out_V_dout,
        p_read1 => layer2_out_V_1_dout,
        p_read2 => layer2_out_V_2_dout,
        p_read3 => layer2_out_V_3_dout,
        ap_return_0 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_0,
        ap_return_1 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_1,
        ap_return_2 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_2,
        ap_return_3 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_3);

    pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0 : component alveo_hls4ml_pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_start,
        ap_done => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_done,
        ap_continue => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_continue,
        ap_idle => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_idle,
        ap_ready => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready,
        p_read => layer4_out_V_dout,
        p_read1 => layer4_out_V_1_dout,
        p_read2 => layer4_out_V_2_dout,
        p_read3 => layer4_out_V_3_dout,
        ap_return => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_return);

    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0 : component alveo_hls4ml_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_start,
        ap_done => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done,
        ap_continue => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue,
        ap_idle => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_idle,
        ap_ready => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_ready,
        p_read => layer5_out_V_dout,
        ap_return_0 => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_0,
        ap_return_1 => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_1,
        ap_return_2 => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_2,
        ap_return_3 => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_3,
        ap_return_4 => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_4);

    normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0 : component alveo_hls4ml_normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_start,
        ap_done => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done,
        ap_continue => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue,
        ap_idle => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_idle,
        ap_ready => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready,
        p_read => layer7_out_V_dout,
        p_read1 => layer7_out_V_1_dout,
        p_read2 => layer7_out_V_2_dout,
        p_read3 => layer7_out_V_3_dout,
        p_read4 => layer7_out_V_4_dout,
        ap_return_0 => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_0,
        ap_return_1 => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_1,
        ap_return_2 => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_2,
        ap_return_3 => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_3,
        ap_return_4 => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_4);

    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0 : component alveo_hls4ml_relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_start,
        ap_done => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done,
        ap_continue => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue,
        ap_idle => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_idle,
        ap_ready => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready,
        p_read => layer9_out_V_dout,
        p_read1 => layer9_out_V_1_dout,
        p_read2 => layer9_out_V_2_dout,
        p_read3 => layer9_out_V_3_dout,
        p_read4 => layer9_out_V_4_dout,
        ap_return_0 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_0,
        ap_return_1 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_1,
        ap_return_2 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_2,
        ap_return_3 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_3,
        ap_return_4 => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_4);

    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0 : component alveo_hls4ml_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_start,
        ap_done => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_done,
        ap_continue => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_continue,
        ap_idle => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_idle,
        ap_ready => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready,
        i_dout => i_c_i_dout,
        i_num_data_valid => i_c_i_num_data_valid,
        i_fifo_cap => i_c_i_fifo_cap,
        i_empty_n => i_c_i_empty_n,
        i_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_i_read,
        p_read => layer10_out_V_dout,
        p_read1 => layer10_out_V_1_dout,
        p_read2 => layer10_out_V_2_dout,
        p_read3 => layer10_out_V_3_dout,
        p_read4 => layer10_out_V_4_dout,
        out_buf_0_address0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_address0,
        out_buf_0_ce0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_ce0,
        out_buf_0_we0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_we0,
        out_buf_0_d0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_d0,
        out_buf_1_address0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_address0,
        out_buf_1_ce0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_ce0,
        out_buf_1_we0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_we0,
        out_buf_1_d0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_d0,
        out_buf_2_address0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_address0,
        out_buf_2_ce0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_ce0,
        out_buf_2_we0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_we0,
        out_buf_2_d0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_d0,
        out_buf_3_address0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_address0,
        out_buf_3_ce0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_ce0,
        out_buf_3_we0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_we0,
        out_buf_3_d0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_d0,
        out_buf_4_address0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_address0,
        out_buf_4_ce0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_ce0,
        out_buf_4_we0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_we0,
        out_buf_4_d0 => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_d0);

    i_c_i_U : component alveo_hls4ml_fifo_w13_d8_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_din,
        if_full_n => i_c_i_full_n,
        if_write => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_i_c_i_write,
        if_dout => i_c_i_dout,
        if_num_data_valid => i_c_i_num_data_valid,
        if_fifo_cap => i_c_i_fifo_cap,
        if_empty_n => i_c_i_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_i_read);

    layer2_out_V_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_0,
        if_full_n => layer2_out_V_full_n,
        if_write => ap_channel_done_layer2_out_V,
        if_dout => layer2_out_V_dout,
        if_num_data_valid => layer2_out_V_num_data_valid,
        if_fifo_cap => layer2_out_V_fifo_cap,
        if_empty_n => layer2_out_V_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready);

    layer2_out_V_1_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_1,
        if_full_n => layer2_out_V_1_full_n,
        if_write => ap_channel_done_layer2_out_V_1,
        if_dout => layer2_out_V_1_dout,
        if_num_data_valid => layer2_out_V_1_num_data_valid,
        if_fifo_cap => layer2_out_V_1_fifo_cap,
        if_empty_n => layer2_out_V_1_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready);

    layer2_out_V_2_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_2,
        if_full_n => layer2_out_V_2_full_n,
        if_write => ap_channel_done_layer2_out_V_2,
        if_dout => layer2_out_V_2_dout,
        if_num_data_valid => layer2_out_V_2_num_data_valid,
        if_fifo_cap => layer2_out_V_2_fifo_cap,
        if_empty_n => layer2_out_V_2_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready);

    layer2_out_V_3_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_return_3,
        if_full_n => layer2_out_V_3_full_n,
        if_write => ap_channel_done_layer2_out_V_3,
        if_dout => layer2_out_V_3_dout,
        if_num_data_valid => layer2_out_V_3_num_data_valid,
        if_fifo_cap => layer2_out_V_3_fifo_cap,
        if_empty_n => layer2_out_V_3_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_ready);

    layer4_out_V_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_0,
        if_full_n => layer4_out_V_full_n,
        if_write => ap_channel_done_layer4_out_V,
        if_dout => layer4_out_V_dout,
        if_num_data_valid => layer4_out_V_num_data_valid,
        if_fifo_cap => layer4_out_V_fifo_cap,
        if_empty_n => layer4_out_V_empty_n,
        if_read => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready);

    layer4_out_V_1_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_1,
        if_full_n => layer4_out_V_1_full_n,
        if_write => ap_channel_done_layer4_out_V_1,
        if_dout => layer4_out_V_1_dout,
        if_num_data_valid => layer4_out_V_1_num_data_valid,
        if_fifo_cap => layer4_out_V_1_fifo_cap,
        if_empty_n => layer4_out_V_1_empty_n,
        if_read => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready);

    layer4_out_V_2_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_2,
        if_full_n => layer4_out_V_2_full_n,
        if_write => ap_channel_done_layer4_out_V_2,
        if_dout => layer4_out_V_2_dout,
        if_num_data_valid => layer4_out_V_2_num_data_valid,
        if_fifo_cap => layer4_out_V_2_fifo_cap,
        if_empty_n => layer4_out_V_2_empty_n,
        if_read => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready);

    layer4_out_V_3_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_return_3,
        if_full_n => layer4_out_V_3_full_n,
        if_write => ap_channel_done_layer4_out_V_3,
        if_dout => layer4_out_V_3_dout,
        if_num_data_valid => layer4_out_V_3_num_data_valid,
        if_fifo_cap => layer4_out_V_3_fifo_cap,
        if_empty_n => layer4_out_V_3_empty_n,
        if_read => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_ready);

    layer5_out_V_U : component alveo_hls4ml_fifo_w10_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_return,
        if_full_n => layer5_out_V_full_n,
        if_write => pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_done,
        if_dout => layer5_out_V_dout,
        if_num_data_valid => layer5_out_V_num_data_valid,
        if_fifo_cap => layer5_out_V_fifo_cap,
        if_empty_n => layer5_out_V_empty_n,
        if_read => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_ready);

    layer7_out_V_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_0,
        if_full_n => layer7_out_V_full_n,
        if_write => ap_channel_done_layer7_out_V,
        if_dout => layer7_out_V_dout,
        if_num_data_valid => layer7_out_V_num_data_valid,
        if_fifo_cap => layer7_out_V_fifo_cap,
        if_empty_n => layer7_out_V_empty_n,
        if_read => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready);

    layer7_out_V_1_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_1,
        if_full_n => layer7_out_V_1_full_n,
        if_write => ap_channel_done_layer7_out_V_1,
        if_dout => layer7_out_V_1_dout,
        if_num_data_valid => layer7_out_V_1_num_data_valid,
        if_fifo_cap => layer7_out_V_1_fifo_cap,
        if_empty_n => layer7_out_V_1_empty_n,
        if_read => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready);

    layer7_out_V_2_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_2,
        if_full_n => layer7_out_V_2_full_n,
        if_write => ap_channel_done_layer7_out_V_2,
        if_dout => layer7_out_V_2_dout,
        if_num_data_valid => layer7_out_V_2_num_data_valid,
        if_fifo_cap => layer7_out_V_2_fifo_cap,
        if_empty_n => layer7_out_V_2_empty_n,
        if_read => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready);

    layer7_out_V_3_U : component alveo_hls4ml_fifo_w10_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_3,
        if_full_n => layer7_out_V_3_full_n,
        if_write => ap_channel_done_layer7_out_V_3,
        if_dout => layer7_out_V_3_dout,
        if_num_data_valid => layer7_out_V_3_num_data_valid,
        if_fifo_cap => layer7_out_V_3_fifo_cap,
        if_empty_n => layer7_out_V_3_empty_n,
        if_read => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready);

    layer7_out_V_4_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_return_4,
        if_full_n => layer7_out_V_4_full_n,
        if_write => ap_channel_done_layer7_out_V_4,
        if_dout => layer7_out_V_4_dout,
        if_num_data_valid => layer7_out_V_4_num_data_valid,
        if_fifo_cap => layer7_out_V_4_fifo_cap,
        if_empty_n => layer7_out_V_4_empty_n,
        if_read => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_ready);

    layer9_out_V_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_0,
        if_full_n => layer9_out_V_full_n,
        if_write => ap_channel_done_layer9_out_V,
        if_dout => layer9_out_V_dout,
        if_num_data_valid => layer9_out_V_num_data_valid,
        if_fifo_cap => layer9_out_V_fifo_cap,
        if_empty_n => layer9_out_V_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready);

    layer9_out_V_1_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_1,
        if_full_n => layer9_out_V_1_full_n,
        if_write => ap_channel_done_layer9_out_V_1,
        if_dout => layer9_out_V_1_dout,
        if_num_data_valid => layer9_out_V_1_num_data_valid,
        if_fifo_cap => layer9_out_V_1_fifo_cap,
        if_empty_n => layer9_out_V_1_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready);

    layer9_out_V_2_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_2,
        if_full_n => layer9_out_V_2_full_n,
        if_write => ap_channel_done_layer9_out_V_2,
        if_dout => layer9_out_V_2_dout,
        if_num_data_valid => layer9_out_V_2_num_data_valid,
        if_fifo_cap => layer9_out_V_2_fifo_cap,
        if_empty_n => layer9_out_V_2_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready);

    layer9_out_V_3_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_3,
        if_full_n => layer9_out_V_3_full_n,
        if_write => ap_channel_done_layer9_out_V_3,
        if_dout => layer9_out_V_3_dout,
        if_num_data_valid => layer9_out_V_3_num_data_valid,
        if_fifo_cap => layer9_out_V_3_fifo_cap,
        if_empty_n => layer9_out_V_3_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready);

    layer9_out_V_4_U : component alveo_hls4ml_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_return_4,
        if_full_n => layer9_out_V_4_full_n,
        if_write => ap_channel_done_layer9_out_V_4,
        if_dout => layer9_out_V_4_dout,
        if_num_data_valid => layer9_out_V_4_num_data_valid,
        if_fifo_cap => layer9_out_V_4_fifo_cap,
        if_empty_n => layer9_out_V_4_empty_n,
        if_read => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_ready);

    layer10_out_V_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_0,
        if_full_n => layer10_out_V_full_n,
        if_write => ap_channel_done_layer10_out_V,
        if_dout => layer10_out_V_dout,
        if_num_data_valid => layer10_out_V_num_data_valid,
        if_fifo_cap => layer10_out_V_fifo_cap,
        if_empty_n => layer10_out_V_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready);

    layer10_out_V_1_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_1,
        if_full_n => layer10_out_V_1_full_n,
        if_write => ap_channel_done_layer10_out_V_1,
        if_dout => layer10_out_V_1_dout,
        if_num_data_valid => layer10_out_V_1_num_data_valid,
        if_fifo_cap => layer10_out_V_1_fifo_cap,
        if_empty_n => layer10_out_V_1_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready);

    layer10_out_V_2_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_2,
        if_full_n => layer10_out_V_2_full_n,
        if_write => ap_channel_done_layer10_out_V_2,
        if_dout => layer10_out_V_2_dout,
        if_num_data_valid => layer10_out_V_2_num_data_valid,
        if_fifo_cap => layer10_out_V_2_fifo_cap,
        if_empty_n => layer10_out_V_2_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready);

    layer10_out_V_3_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_3,
        if_full_n => layer10_out_V_3_full_n,
        if_write => ap_channel_done_layer10_out_V_3,
        if_dout => layer10_out_V_3_dout,
        if_num_data_valid => layer10_out_V_3_num_data_valid,
        if_fifo_cap => layer10_out_V_3_fifo_cap,
        if_empty_n => layer10_out_V_3_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready);

    layer10_out_V_4_U : component alveo_hls4ml_fifo_w6_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_return_4,
        if_full_n => layer10_out_V_4_full_n,
        if_write => ap_channel_done_layer10_out_V_4,
        if_dout => layer10_out_V_4_dout,
        if_num_data_valid => layer10_out_V_4_num_data_valid,
        if_fifo_cap => layer10_out_V_4_fifo_cap,
        if_empty_n => layer10_out_V_4_empty_n,
        if_read => dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_ready);





    ap_sync_reg_channel_write_layer10_out_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer10_out_V <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer10_out_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer10_out_V <= ap_sync_channel_write_layer10_out_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer10_out_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer10_out_V_1 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer10_out_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer10_out_V_1 <= ap_sync_channel_write_layer10_out_V_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer10_out_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer10_out_V_2 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer10_out_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer10_out_V_2 <= ap_sync_channel_write_layer10_out_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer10_out_V_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer10_out_V_3 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer10_out_V_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer10_out_V_3 <= ap_sync_channel_write_layer10_out_V_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer10_out_V_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer10_out_V_4 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer10_out_V_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer10_out_V_4 <= ap_sync_channel_write_layer10_out_V_4;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer2_out_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer2_out_V <= ap_const_logic_0;
            else
                if (((conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer2_out_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer2_out_V <= ap_sync_channel_write_layer2_out_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer2_out_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer2_out_V_1 <= ap_const_logic_0;
            else
                if (((conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer2_out_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer2_out_V_1 <= ap_sync_channel_write_layer2_out_V_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer2_out_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer2_out_V_2 <= ap_const_logic_0;
            else
                if (((conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer2_out_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer2_out_V_2 <= ap_sync_channel_write_layer2_out_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer2_out_V_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer2_out_V_3 <= ap_const_logic_0;
            else
                if (((conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer2_out_V_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer2_out_V_3 <= ap_sync_channel_write_layer2_out_V_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer4_out_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer4_out_V <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer4_out_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer4_out_V <= ap_sync_channel_write_layer4_out_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer4_out_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer4_out_V_1 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer4_out_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer4_out_V_1 <= ap_sync_channel_write_layer4_out_V_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer4_out_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer4_out_V_2 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer4_out_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer4_out_V_2 <= ap_sync_channel_write_layer4_out_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer4_out_V_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer4_out_V_3 <= ap_const_logic_0;
            else
                if (((relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer4_out_V_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer4_out_V_3 <= ap_sync_channel_write_layer4_out_V_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer7_out_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer7_out_V <= ap_const_logic_0;
            else
                if (((dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer7_out_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer7_out_V <= ap_sync_channel_write_layer7_out_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer7_out_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer7_out_V_1 <= ap_const_logic_0;
            else
                if (((dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer7_out_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer7_out_V_1 <= ap_sync_channel_write_layer7_out_V_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer7_out_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer7_out_V_2 <= ap_const_logic_0;
            else
                if (((dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer7_out_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer7_out_V_2 <= ap_sync_channel_write_layer7_out_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer7_out_V_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer7_out_V_3 <= ap_const_logic_0;
            else
                if (((dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer7_out_V_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer7_out_V_3 <= ap_sync_channel_write_layer7_out_V_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer7_out_V_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer7_out_V_4 <= ap_const_logic_0;
            else
                if (((dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer7_out_V_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer7_out_V_4 <= ap_sync_channel_write_layer7_out_V_4;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer9_out_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer9_out_V <= ap_const_logic_0;
            else
                if (((normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer9_out_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer9_out_V <= ap_sync_channel_write_layer9_out_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer9_out_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer9_out_V_1 <= ap_const_logic_0;
            else
                if (((normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer9_out_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer9_out_V_1 <= ap_sync_channel_write_layer9_out_V_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer9_out_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer9_out_V_2 <= ap_const_logic_0;
            else
                if (((normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer9_out_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer9_out_V_2 <= ap_sync_channel_write_layer9_out_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer9_out_V_3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer9_out_V_3 <= ap_const_logic_0;
            else
                if (((normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer9_out_V_3 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer9_out_V_3 <= ap_sync_channel_write_layer9_out_V_3;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_layer9_out_V_4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_layer9_out_V_4 <= ap_const_logic_0;
            else
                if (((normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_layer9_out_V_4 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_layer9_out_V_4 <= ap_sync_channel_write_layer9_out_V_4;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_layer10_out_V <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and (ap_sync_reg_channel_write_layer10_out_V xor ap_const_logic_1));
    ap_channel_done_layer10_out_V_1 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and (ap_sync_reg_channel_write_layer10_out_V_1 xor ap_const_logic_1));
    ap_channel_done_layer10_out_V_2 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and (ap_sync_reg_channel_write_layer10_out_V_2 xor ap_const_logic_1));
    ap_channel_done_layer10_out_V_3 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and (ap_sync_reg_channel_write_layer10_out_V_3 xor ap_const_logic_1));
    ap_channel_done_layer10_out_V_4 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_done and (ap_sync_reg_channel_write_layer10_out_V_4 xor ap_const_logic_1));
    ap_channel_done_layer2_out_V <= ((ap_sync_reg_channel_write_layer2_out_V xor ap_const_logic_1) and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done);
    ap_channel_done_layer2_out_V_1 <= ((ap_sync_reg_channel_write_layer2_out_V_1 xor ap_const_logic_1) and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done);
    ap_channel_done_layer2_out_V_2 <= ((ap_sync_reg_channel_write_layer2_out_V_2 xor ap_const_logic_1) and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done);
    ap_channel_done_layer2_out_V_3 <= ((ap_sync_reg_channel_write_layer2_out_V_3 xor ap_const_logic_1) and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_done);
    ap_channel_done_layer4_out_V <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and (ap_sync_reg_channel_write_layer4_out_V xor ap_const_logic_1));
    ap_channel_done_layer4_out_V_1 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and (ap_sync_reg_channel_write_layer4_out_V_1 xor ap_const_logic_1));
    ap_channel_done_layer4_out_V_2 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and (ap_sync_reg_channel_write_layer4_out_V_2 xor ap_const_logic_1));
    ap_channel_done_layer4_out_V_3 <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_done and (ap_sync_reg_channel_write_layer4_out_V_3 xor ap_const_logic_1));
    ap_channel_done_layer7_out_V <= ((ap_sync_reg_channel_write_layer7_out_V xor ap_const_logic_1) and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done);
    ap_channel_done_layer7_out_V_1 <= ((ap_sync_reg_channel_write_layer7_out_V_1 xor ap_const_logic_1) and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done);
    ap_channel_done_layer7_out_V_2 <= ((ap_sync_reg_channel_write_layer7_out_V_2 xor ap_const_logic_1) and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done);
    ap_channel_done_layer7_out_V_3 <= ((ap_sync_reg_channel_write_layer7_out_V_3 xor ap_const_logic_1) and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done);
    ap_channel_done_layer7_out_V_4 <= ((ap_sync_reg_channel_write_layer7_out_V_4 xor ap_const_logic_1) and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_done);
    ap_channel_done_layer9_out_V <= (normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and (ap_sync_reg_channel_write_layer9_out_V xor ap_const_logic_1));
    ap_channel_done_layer9_out_V_1 <= (normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and (ap_sync_reg_channel_write_layer9_out_V_1 xor ap_const_logic_1));
    ap_channel_done_layer9_out_V_2 <= (normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and (ap_sync_reg_channel_write_layer9_out_V_2 xor ap_const_logic_1));
    ap_channel_done_layer9_out_V_3 <= (normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and (ap_sync_reg_channel_write_layer9_out_V_3 xor ap_const_logic_1));
    ap_channel_done_layer9_out_V_4 <= (normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_done and (ap_sync_reg_channel_write_layer9_out_V_4 xor ap_const_logic_1));
    ap_done <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_done;
    ap_idle <= (relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_idle and relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_idle and pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_idle and normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_idle and (layer10_out_V_4_empty_n xor ap_const_logic_1) and (layer10_out_V_3_empty_n xor ap_const_logic_1) and (layer10_out_V_2_empty_n xor ap_const_logic_1) and (layer10_out_V_1_empty_n xor ap_const_logic_1) and (layer10_out_V_empty_n xor ap_const_logic_1) and (layer9_out_V_4_empty_n xor ap_const_logic_1) and (layer9_out_V_3_empty_n xor ap_const_logic_1) and (layer9_out_V_2_empty_n xor ap_const_logic_1) and (layer9_out_V_1_empty_n xor ap_const_logic_1) and (layer9_out_V_empty_n xor ap_const_logic_1) and (layer7_out_V_4_empty_n xor ap_const_logic_1) and (layer7_out_V_3_empty_n xor ap_const_logic_1) and (layer7_out_V_2_empty_n xor ap_const_logic_1) and (layer7_out_V_1_empty_n xor ap_const_logic_1) and (layer7_out_V_empty_n xor ap_const_logic_1) and (layer5_out_V_empty_n xor ap_const_logic_1) and (layer4_out_V_3_empty_n xor ap_const_logic_1) and (layer4_out_V_2_empty_n xor ap_const_logic_1) and (layer4_out_V_1_empty_n xor ap_const_logic_1) and (layer4_out_V_empty_n xor ap_const_logic_1) and (layer2_out_V_3_empty_n xor ap_const_logic_1) and (layer2_out_V_2_empty_n xor ap_const_logic_1) and (layer2_out_V_1_empty_n xor ap_const_logic_1) and (layer2_out_V_empty_n xor ap_const_logic_1) and dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_idle and dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_idle and conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_idle);
    ap_ready <= conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_ready;
    ap_sync_channel_write_layer10_out_V <= ((layer10_out_V_full_n and ap_channel_done_layer10_out_V) or ap_sync_reg_channel_write_layer10_out_V);
    ap_sync_channel_write_layer10_out_V_1 <= ((layer10_out_V_1_full_n and ap_channel_done_layer10_out_V_1) or ap_sync_reg_channel_write_layer10_out_V_1);
    ap_sync_channel_write_layer10_out_V_2 <= ((layer10_out_V_2_full_n and ap_channel_done_layer10_out_V_2) or ap_sync_reg_channel_write_layer10_out_V_2);
    ap_sync_channel_write_layer10_out_V_3 <= ((layer10_out_V_3_full_n and ap_channel_done_layer10_out_V_3) or ap_sync_reg_channel_write_layer10_out_V_3);
    ap_sync_channel_write_layer10_out_V_4 <= ((layer10_out_V_4_full_n and ap_channel_done_layer10_out_V_4) or ap_sync_reg_channel_write_layer10_out_V_4);
    ap_sync_channel_write_layer2_out_V <= ((layer2_out_V_full_n and ap_channel_done_layer2_out_V) or ap_sync_reg_channel_write_layer2_out_V);
    ap_sync_channel_write_layer2_out_V_1 <= ((layer2_out_V_1_full_n and ap_channel_done_layer2_out_V_1) or ap_sync_reg_channel_write_layer2_out_V_1);
    ap_sync_channel_write_layer2_out_V_2 <= ((layer2_out_V_2_full_n and ap_channel_done_layer2_out_V_2) or ap_sync_reg_channel_write_layer2_out_V_2);
    ap_sync_channel_write_layer2_out_V_3 <= ((layer2_out_V_3_full_n and ap_channel_done_layer2_out_V_3) or ap_sync_reg_channel_write_layer2_out_V_3);
    ap_sync_channel_write_layer4_out_V <= ((layer4_out_V_full_n and ap_channel_done_layer4_out_V) or ap_sync_reg_channel_write_layer4_out_V);
    ap_sync_channel_write_layer4_out_V_1 <= ((layer4_out_V_1_full_n and ap_channel_done_layer4_out_V_1) or ap_sync_reg_channel_write_layer4_out_V_1);
    ap_sync_channel_write_layer4_out_V_2 <= ((layer4_out_V_2_full_n and ap_channel_done_layer4_out_V_2) or ap_sync_reg_channel_write_layer4_out_V_2);
    ap_sync_channel_write_layer4_out_V_3 <= ((layer4_out_V_3_full_n and ap_channel_done_layer4_out_V_3) or ap_sync_reg_channel_write_layer4_out_V_3);
    ap_sync_channel_write_layer7_out_V <= ((layer7_out_V_full_n and ap_channel_done_layer7_out_V) or ap_sync_reg_channel_write_layer7_out_V);
    ap_sync_channel_write_layer7_out_V_1 <= ((layer7_out_V_1_full_n and ap_channel_done_layer7_out_V_1) or ap_sync_reg_channel_write_layer7_out_V_1);
    ap_sync_channel_write_layer7_out_V_2 <= ((layer7_out_V_2_full_n and ap_channel_done_layer7_out_V_2) or ap_sync_reg_channel_write_layer7_out_V_2);
    ap_sync_channel_write_layer7_out_V_3 <= ((layer7_out_V_3_full_n and ap_channel_done_layer7_out_V_3) or ap_sync_reg_channel_write_layer7_out_V_3);
    ap_sync_channel_write_layer7_out_V_4 <= ((layer7_out_V_4_full_n and ap_channel_done_layer7_out_V_4) or ap_sync_reg_channel_write_layer7_out_V_4);
    ap_sync_channel_write_layer9_out_V <= ((layer9_out_V_full_n and ap_channel_done_layer9_out_V) or ap_sync_reg_channel_write_layer9_out_V);
    ap_sync_channel_write_layer9_out_V_1 <= ((layer9_out_V_1_full_n and ap_channel_done_layer9_out_V_1) or ap_sync_reg_channel_write_layer9_out_V_1);
    ap_sync_channel_write_layer9_out_V_2 <= ((layer9_out_V_2_full_n and ap_channel_done_layer9_out_V_2) or ap_sync_reg_channel_write_layer9_out_V_2);
    ap_sync_channel_write_layer9_out_V_3 <= ((layer9_out_V_3_full_n and ap_channel_done_layer9_out_V_3) or ap_sync_reg_channel_write_layer9_out_V_3);
    ap_sync_channel_write_layer9_out_V_4 <= ((layer9_out_V_4_full_n and ap_channel_done_layer9_out_V_4) or ap_sync_reg_channel_write_layer9_out_V_4);
    conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_continue <= (ap_sync_channel_write_layer2_out_V_3 and ap_sync_channel_write_layer2_out_V_2 and ap_sync_channel_write_layer2_out_V_1 and ap_sync_channel_write_layer2_out_V);
    conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_ap_start <= ap_start;
    conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_write <= ap_const_logic_0;
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_continue <= (ap_sync_channel_write_layer7_out_V_4 and ap_sync_channel_write_layer7_out_V_3 and ap_sync_channel_write_layer7_out_V_2 and ap_sync_channel_write_layer7_out_V_1 and ap_sync_channel_write_layer7_out_V);
    dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_U0_ap_start <= layer5_out_V_empty_n;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_continue <= ap_continue;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_ap_start <= (layer10_out_V_empty_n and layer10_out_V_4_empty_n and layer10_out_V_3_empty_n and layer10_out_V_2_empty_n and layer10_out_V_1_empty_n);
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_write <= ap_const_logic_0;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_write <= ap_const_logic_0;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_write <= ap_const_logic_0;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_write <= ap_const_logic_0;
    dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_write <= ap_const_logic_0;
    in_buf_address0 <= conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_address0;
    in_buf_address1 <= ap_const_lv13_0;
    in_buf_ce0 <= conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_ce0;
    in_buf_ce1 <= ap_const_logic_0;
    in_buf_d0 <= ap_const_lv768_lc_1;
    in_buf_d1 <= ap_const_lv768_lc_1;
    in_buf_read <= conv_2d_cl_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_2_U0_in_buf_write;
    in_buf_we0 <= ap_const_logic_0;
    in_buf_we1 <= ap_const_logic_0;
    normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_continue <= (ap_sync_channel_write_layer9_out_V_4 and ap_sync_channel_write_layer9_out_V_3 and ap_sync_channel_write_layer9_out_V_2 and ap_sync_channel_write_layer9_out_V_1 and ap_sync_channel_write_layer9_out_V);
    normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config9_U0_ap_start <= (layer7_out_V_empty_n and layer7_out_V_4_empty_n and layer7_out_V_3_empty_n and layer7_out_V_2_empty_n and layer7_out_V_1_empty_n);
    out_buf_0_address0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_address0;
    out_buf_0_address1 <= ap_const_lv13_0;
    out_buf_0_ce0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_ce0;
    out_buf_0_ce1 <= ap_const_logic_0;
    out_buf_0_d0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_d0;
    out_buf_0_d1 <= ap_const_lv13_0;
    out_buf_0_we0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_we0;
    out_buf_0_we1 <= ap_const_logic_0;
    out_buf_0_write <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_0_write;
    out_buf_1_address0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_address0;
    out_buf_1_address1 <= ap_const_lv13_0;
    out_buf_1_ce0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_ce0;
    out_buf_1_ce1 <= ap_const_logic_0;
    out_buf_1_d0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_d0;
    out_buf_1_d1 <= ap_const_lv13_0;
    out_buf_1_we0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_we0;
    out_buf_1_we1 <= ap_const_logic_0;
    out_buf_1_write <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_1_write;
    out_buf_2_address0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_address0;
    out_buf_2_address1 <= ap_const_lv13_0;
    out_buf_2_ce0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_ce0;
    out_buf_2_ce1 <= ap_const_logic_0;
    out_buf_2_d0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_d0;
    out_buf_2_d1 <= ap_const_lv13_0;
    out_buf_2_we0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_we0;
    out_buf_2_we1 <= ap_const_logic_0;
    out_buf_2_write <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_2_write;
    out_buf_3_address0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_address0;
    out_buf_3_address1 <= ap_const_lv13_0;
    out_buf_3_ce0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_ce0;
    out_buf_3_ce1 <= ap_const_logic_0;
    out_buf_3_d0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_d0;
    out_buf_3_d1 <= ap_const_lv13_0;
    out_buf_3_we0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_we0;
    out_buf_3_we1 <= ap_const_logic_0;
    out_buf_3_write <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_3_write;
    out_buf_4_address0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_address0;
    out_buf_4_address1 <= ap_const_lv13_0;
    out_buf_4_ce0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_ce0;
    out_buf_4_ce1 <= ap_const_logic_0;
    out_buf_4_d0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_d0;
    out_buf_4_d1 <= ap_const_lv13_0;
    out_buf_4_we0 <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_we0;
    out_buf_4_we1 <= ap_const_logic_0;
    out_buf_4_write <= dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config11_U0_out_buf_4_write;
    pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_continue <= layer5_out_V_full_n;
    pooling2d_cl_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_U0_ap_start <= (layer4_out_V_empty_n and layer4_out_V_3_empty_n and layer4_out_V_2_empty_n and layer4_out_V_1_empty_n);
    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_continue <= (ap_sync_channel_write_layer10_out_V_4 and ap_sync_channel_write_layer10_out_V_3 and ap_sync_channel_write_layer10_out_V_2 and ap_sync_channel_write_layer10_out_V_1 and ap_sync_channel_write_layer10_out_V);
    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config10_U0_ap_start <= (layer9_out_V_empty_n and layer9_out_V_4_empty_n and layer9_out_V_3_empty_n and layer9_out_V_2_empty_n and layer9_out_V_1_empty_n);
    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_continue <= (ap_sync_channel_write_layer4_out_V_3 and ap_sync_channel_write_layer4_out_V_2 and ap_sync_channel_write_layer4_out_V_1 and ap_sync_channel_write_layer4_out_V);
    relu_ap_fixed_16_6_5_3_0_ap_ufixed_6_0_4_0_0_relu_config4_U0_ap_start <= (layer2_out_V_empty_n and layer2_out_V_3_empty_n and layer2_out_V_2_empty_n and layer2_out_V_1_empty_n);
end behav;
